name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: CI with softoken
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        name: [fedora-gcc, fedora-clang, debian-clang]
        include:
          - name: fedora-gcc
            distro: fedora:latest
            compiler: gcc
          - name: fedora-clang
            distro: fedora:latest
            compiler: clang
          - name: debian-clang
            distro: debian:sid
            compiler: clang
    steps:
    - uses: actions/checkout@v3
      name: Checkout Repository
    - name: Build and Test
      run: ./.github/scripts/run_dockerized.sh
      env:
        DISTRO: ${{ matrix.distro }}
        COMPILER: ${{ matrix.compiler }}
        ACTION: check
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: Test logs ${{ matrix.name }}
        path: |
          tests/test.sh.log
          tests/openssl.cnf
          tests/tmp/p11prov-debug.log
          tests/tmp/debugvars
          config.log
    - name: Distribution Check
      run: ./.github/scripts/run_dockerized.sh
      env:
        DISTRO: ${{ matrix.distro }}
        COMPILER: ${{ matrix.compiler }}
        ACTION: distcheck
