name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: CI with softoken
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        name: [fedora-gcc, fedora-clang, debian-clang, fedora-distcheck]
        include:
          - name: fedora-gcc
            container: fedora:latest
            compiler: gcc
            action: check
          - name: fedora-clang
            container: fedora:latest
            compiler: clang
            action: check
          - name: debian-clang
            container: debian:sid
            compiler: clang
            action: check
          - name: fedora-distcheck
            container: fedora:latest
            compiler: gcc
            action: distcheck
    container: ${{ matrix.container }}
    steps:
    - name: Install Dependencies
      run: |
          if [ -f /etc/fedora-release ]; then
            dnf -y install git ${{ matrix.compiler }} automake libtool \
              pkgconf-pkg-config autoconf-archive openssl-devel openssl \
              nss-softokn nss-tools nss-softokn-devel
          fi
          if [ -f /etc/debian_version ]; then
            apt-get -q update
            apt-get -yq install git ${{ matrix.compiler }} make automake \
              libtool pkg-config autoconf-archive libssl-dev openssl \
              libnss3 libnss3-tools libnss3-dev
          fi
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Setup
      run: |
        autoreconf -fiv
        CC=${{ matrix.compiler }} ./configure
    - name: Build and Test
      run: make ${{ matrix.action }}
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: Test logs ${{ matrix.name }}
        path: |
          tests/test.sh.log
          tests/openssl.cnf
          tests/tmp/p11prov-debug.log
          tests/tmp/debugvars
          config.log
