name: Coverity Scan

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron:  '41 3 * * 0'

jobs:
  coverity:
    name: Coverity Scan
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      name: Checkout Repository
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf-archive libnss3 libnss3-tools libnss3-dev clang
    - name: Setup
      run: |
        autoreconf -fiv
        ./configure
    - name: Check for changes
      run: |
          echo "RUN_COV=0" >> $GITHUB_ENV;
          DIFF=`git log --since=1week | wc -l`
          if [ x${DIFF} != "x0" ]; then
            echo "RUN_COV=1" >> $GITHUB_ENV;
          fi
    - name: Coverity Scan
      if: env.RUN_COV == 1
      uses: vapier/coverity-scan-action@v1
      with:
        project: "PKCS%2311+Provider"
        email: ${{ secrets.COVERITY_SCAN_EMAIL }}
        token: ${{ secrets.COVERITY_SCAN_TOKEN }}
